version: '3.7'

services:
  db:
    image: postgres:9.6
    container_name: tcc-db
    restart: "no"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: python:3.8
    container_name: tcc-api
    restart: "no"
    working_dir: /usr/src/app
    command: bash -c "(cd graphene-django && make dev-setup) &&
                      pip install -e graphene-django &&
                      pip install -r sample_app/requirements.txt &&
                      python sample_app/manage.py migrate &&
                      python sample_app/manage.py runserver 0.0.0.0:8000"
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
      - "34404:34404"
    volumes:
      - .:/usr/src/app

volumes:
  db-data:
