version: '3.7'

services:
  api:
    image: python:3.8
    container_name: api
    restart: "no"
    working_dir: /usr/src/app
    command: bash -c "(cd graphene-django && make dev-setup) &&
                      pip install -r sample_app/requirements.txt &&
                      python sample_app/manage.py migrate &&
                      python sample_app/manage.py runserver 0.0.0.0:8000"
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
