# Generated by Django 3.1.8 on 2021-09-23 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210923_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='effectiveness')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='base.vaccine', verbose_name='VACCINE')),
            ],
            options={
                'verbose_name': 'vaccine research',
                'verbose_name_plural': 'vaccine researches',
            },
        ),
        migrations.CreateModel(
            name='Infection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lethal', models.BooleanField(verbose_name='lethal')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infections', to='base.disease', verbose_name='disease')),
            ],
            options={
                'verbose_name': 'infection',
                'verbose_name_plural': 'infections',
            },
        ),
    ]
